# Generated by Django 6.1 on 2026-09-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, choices=[('up', 'Thumbs up'), ('down', 'Thumbs down')], help_text="Customer's thumbs up/down on this reply, if given.", max_length=4, null=True),
        ),
    ]