# Generated by Django 6.1 on 2026-09-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="live_site_id",
            field=models.CharField(
                blank=True,
                help_text="The real site's product id, once this row has been matched to it.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In stock"),
                    ("low_stock", "Low stock"),
                    ("out_of_stock", "Out of stock"),
                ],
                default="in_stock",
                help_text="Coarse status synced from the live site - not an exact count.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
